version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: task_manager_db
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - task_manager_network

  phppgadmin:
    image: dpage/pgadmin4:latest
    container_name: task_manager_pgadmin
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_LISTEN_ADDRESS: 127.0.0.1
    ports:
      - "127.0.0.1:5050:80"
    depends_on:
      - postgres
    networks:
      - task_manager_network

volumes:
  postgres_data:

networks:
  task_manager_network:
    driver: bridge